version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
    command: cargo watch -x run

  ai:
    build:
      context: ./ai-service
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app
    environment:
      - PYTHONPATH=/app/src
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload 