# .github/workflows/ai.yml
name: AI Service CI

on:
  push:
    paths:
      - 'ai-service/**'
      - '.github/workflows/ai.yml'
      - '.pre-commit-config.yaml'
  pull_request:
    paths:
      - 'ai-service/**'
      - '.github/workflows/ai.yml'
      - '.pre-commit-config.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mjs_ai_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./ai-service

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Install pre-commit hooks
      run: pre-commit install

    - name: Run pre-commit on all files
      run: pre-commit run --all-files

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run type checking
      run: poetry run mypy .

    - name: Test
      run: poetry run pytest --cov
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mjs_ai_test
