# .github/workflows/ai.yml
name: AI Service CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ai/**'
      - '.github/workflows/ai.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ai/**'
      - '.github/workflows/ai.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mjs_ai_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./ai

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: poetry install

    - name: Code Quality
      run: |
        poetry run black . --check
        poetry run isort . --check
        poetry run mypy .

    - name: Test
      run: poetry run pytest --cov
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mjs_ai_test